### ISSUE TITLE
add "old" qidi printers

### ISSUE THREAD

**Issue by shubukin** [QIDITECH/QIDISlicer#20]
it is possible to have all your printer for example x-max in qidi-slicer?

**Comment by QIDITECH** [comment]
I'm very sorry, because the old model and the new model are too different, so we don't have enough time to adapt. Print parameters, wifi connections, thumbnails, etc., to perfectly fit older models, it takes a lot of manpower and time. We have no plans to do this for the time being, and will devote our limited energy to the development of new technologies, which are more valuable. Thank you for your understanding and support.

If you only need a simple configuration file, you can contact after-sales service to get it.
https://qidi3d.com/pages/warranty-policy-after-sales-support
