### ISSUE TITLE
Klipper-Integration/Update 

### ISSUE THREAD

**Issue by Scraynos** [QIDITECH/QIDISlicer#91]
Dear Qidi Support Team,

I am experiencing issues with the integration of Klipper, KlipperScreen, and Moonraker through the Qidi Slicer. When attempting to use these applications, I receive the following error message:

vbnet
Code kopieren
Application klipper: Attempting Repo Recovery...
Application klipper: Resetting Git Repo...
fatal: unable to access 'https://github.com/Klipper3d/klipper/': server certificate verification failed. CAfile: none CRLfile: none 
Application klipper: Attempting Repo Recovery...
Git Repo klipper: Starting Clone Recovery...
Cloning into '/home/mks/.klipper_repo_backup'...
fatal: unable to access 'https://github.com/Klipper3d/klipper.git/': server certificate verification failed. CAfile: none CRLfile: none
Git Repo klipper: Git Clone Failed
Error Recovering klipper
I have already checked my internet connection and ruled out other network issues. Additionally, I am unable to use the printer, as it only shows that Klipper is not up to date. Could you please assist me in resolving this problem?

Thank you in advance for your support!

Best regards,
Julian

![Screenshot 2024-09-25 002109](https://github.com/user-attachments/assets/56840031-b5f2-4333-9bba-d7009944758f)

**Comment by QIDITECH** [comment]
In order to add and adapt some functions, we have made some modifications to klipper and moonraker, so it is not compatible with the official version, please do not easily update klipper, moonraker and other software.
In order to recover, you can only refresh the system and make everything back to normal. Contact after-sales service for detailed operations and guides.
